### ISSUE TITLE
what function module belongs to.

### ISSUE THREAD

**Issue by cloudy4next** [geyuying/PF-AFN#41]
save_checkpoint(model.module, os.path.join(opt.checkpoints_dir, opt.name, 'PBAFN_warp_epoch_%03d.pth' % (epoch+1)))

**Comment by cloudy4next** [comment]
Sorry for inconvenience

**Comment by soumyajit123dev** [comment]
@cloudy4next  I am also getting a similar error. How did you solve it? 
![error](https://user-images.githubusercontent.com/77043036/127202192-60da47b0-d965-4938-932f-6f5739bcc8f0.png)


I got the code to run if I remove the word "module". Basically, instead of "model.module", I just write "model". But is this the right way?

**Comment by cloudy4next** [comment]
Just remove (module) from each stage script 😃
```
module.model.something 
To
model.something 
```

**Comment by cloudy4next** [comment]
Just remove (module) from each stage script 😃
```
module.model.something 
To
model.something 

```
@soumyajit123dev
